---
title: "Factorisation de Bunch-Parlett et Bunch-Kaufman"
subtitle: "MTH8211 - Projet phase 3"
author:
  - name: Hortense Beaudoin et Téo Dumoutier
    email: hortense.beaudoin@polymtl.ca et teo.dumoutier@polymtl.ca
    affiliation:
      - name: Polytechnique Montréal
format:
  pdf:
    keep-tex: false
    documentclass: article
    include-in-header:
      - text: |
            \usepackage{xspace}
            \usepackage[francais]{babel}
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
            \usepackage[table]{xcolor}
            \newcommand\y{\cellcolor{green!10}}
            \newcommand\x{\cellcolor{blue!10}}
    geometry:
      - margin=1in
    papersize: letter
    colorlinks: true
    monofont: JuliaMono
    number-sections: true
    urlcolor: blue
engine: julia
---

@sec-description . Description du projet 

@sec-theorie . Théorie

@sec-implementation . Implémentation

@sec-tests . Tests et performance

@sec-discussion . Discussion

@sec-objectifs . Retour sur les objectifs

@sec-references . Références

@sec-annexe . Annexe


# Description du projet {#sec-description}

Si on tente de résoudre un système $Ax=b$ où $A$ est dense, plusiques solutions existent, mais une majorité sont très coûteuses. La décomposition QR et la SVD existent pour toute matrice $A$, y compris les matrices indéfinies (i.e il existe $x$ t.q $x^TAx\le 0$ et il existe $y$ t.q $y^TAy\ge 0$), mais elles n'exploitent pas forcément la structure du système à résoudre. 

Certaines structures symétriques sont fréquemment rencontrées lors de la résolution de problèmes. On a par exemple vu en classe qu'une autre manière d'exprimer le problème de moindre carré est de résoudre plutôt le système de point de selle

$$\begin{bmatrix} I & A \\ A^T & 0 \end{bmatrix}\begin{bmatrix} r \\ x \end{bmatrix} = \begin{bmatrix} b \\ 0 \end{bmatrix}$$

où la matrice formée de $A$ et $A^T$ est symétrique et toujours indéfinie. Sous cette forme, le bloc supérieur gauche est bien évidemment inversible, puisqu'il est égal à l'identité. De manière intéressante, toute autre matrice $B$ symétrique non-nulle peut être permutée pour adopter une forme où le bloc supérieur gauche est inversible, soit

$$PBP^T = \begin{bmatrix} E & C^T \\ C & D \end{bmatrix}$$

où $D=D^T$ et $E=E^T$ inversible. Ce type de problème est donc particulièrement fréquent et il est intéressant de s'intéresser à une méthode de résolution où la symétrie des matrices est exploitée. 

La décomposition de Cholesky n'existe pas pour ce genre de système puisque la matrice considérée n'est pas définie-positive, ce qui est une exigence associée à ce type de factorisation. Une factorisation $LDL^*$ pourrait exister, mais pas systématiquement et elle court le risque d'être numériquement instable. Higham illustre bien ce risque dans son livre avec l'exemple suivant:

$$A = \begin{bmatrix} \epsilon & 1 \\ 1 & \epsilon\end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 1/\epsilon & 1\end{bmatrix}\begin{bmatrix} \epsilon & 0 \\ 0 & \epsilon-1/\epsilon\end{bmatrix}\begin{bmatrix} 1 & 1/\epsilon \\ 0 & 1\end{bmatrix}$$

$A$ est symétrique et si $\epsilon< 1$, indéfinie. On remarque que dans le cas où $\epsilon=0$ la factorisation n'existe tout simplement et que le reste du temps, les facteurs $1/\epsilon$ risquent de grossir de manière disproportionnée, menant à un système mal conditionné ou à des erreurs numériques importantes. 

Ce projet va donc plutôt s'intéresser aux factorisations de Bunch-Parlett et Bunch-Kaufman, qui exploitent toutes deux l'idée de permutation mentionnée précédemment. La mise en place algébrique étant la même dans les deux cas, nous allons dès maintenant la présenter brièvement.

# Théorie {#sec-theorie}
## Factorisation en bloc pour matrices symétriques

Tel que mentionné ci-dessus, toute matrice $A\in\mathbb{C}^{n\times n}$ symétrique non-nulle peut être permutée de la manière suivante:

$$PAP^T = \begin{bmatrix} E & C^T \\ C & D \end{bmatrix}$$

où $E\in\mathbb{C}^{s\times s}$, $C\in\mathbb{C}^{n-s\times s}$ et $D\in\mathbb{C}^{(n-s)\times (n-s)}$ avec $s\in{1,2}$ et $E$ inversible. Sous cette forme, il est possible de procéder à la factorisation suivante:

$$PAP^T = \begin{bmatrix} I_s & 0 \\ CE^{-1} & I_{n-s} \end{bmatrix} \begin{bmatrix} E & 0 \\ 0 & D-CE^{-1}C^T \end{bmatrix} \begin{bmatrix} I_s & E^{-1}C^T \\ 0 & I_{n-s} \end{bmatrix}$$

On reconnait $D-CE^{-1}C^T$ comme étant le complément de Schur de $E$ dans la matrice $PAP^T$. Ce complément est aussi symétrique, par symétrie des blocs $E$ et $D$;

$$(D-CE^{-1}C^T)^T = D^T - CE^{-T}C^T = D-CE^{-1}C^T$$

On peut donc répéter le processus sur cette matrice de dimension $(n-s)\times (n-s)$, puis de nouveau et ainsi de suite jusqu'à l'obtention de la factorisation complète. 

À titre d'illustration, imaginons être à l'itération $k$ avec la forme suivante;

$$P_kA_kP_k^T = \begin{bmatrix} E_k & C_k^T \\ C_k & D_k \end{bmatrix} = \begin{bmatrix} I_{s_k} & 0 \\ C_kE_k^{-1} & I_{n-s_k} \end{bmatrix} \begin{bmatrix} E_k & 0 \\ 0 & D_k-C_kE_k^{-1}C_k^T \end{bmatrix} \begin{bmatrix} I_{s_k} & E_k^{-1}C_k^T \\ 0 & I_{n-s_k} \end{bmatrix}$$

On pose alors $A_{k+1} = D_k-C_kE_k^{-1}C_k^T$ et on procède de la même manière.

$$P_{k+1}A_{k+1}P_{k+1}^T = \begin{bmatrix} E_{k+1} & C_{k+1}^T \\ C_{k+1} & D_{k+1} \end{bmatrix} = \begin{bmatrix} I_{s_{k+1}} & 0 \\ C_{k+1}E_k^{-1} & I_{n-(s_k+s_{k+1})} \end{bmatrix} \begin{bmatrix} E_{k+1} & 0 \\ 0 & D_{k+1}-C_{k+1}E_{k+1}^{-1}C_{k+1}^T \end{bmatrix} \begin{bmatrix} I_{s_{k+1}} & E_{k+1}^{-1}C_{k+1}^T \\ 0 & I_{n-(s_k+s_{k+1})} \end{bmatrix}$$

Et ainsi de suite. Les matrices $P$, $L$ et $B$ sont construites de la façon suivante à chaque itération:

$$P_{k+1} = P_{k+1}P_{k}\dots P_1$$
$$L_{k+1} = \begin{bmatrix}I_{s_k} &  0 & 0 \\ (C_kE_k^{-1})[1:s_{k+1},1:s_{k+1}] & I_{s_{k+1}} & 0 \\ (C_kE_k^{-1})[s_{k+1}+1:n,1:s_{k+1}] & (C_{k+1}E_{k+1}^{-1}) & I_{n-(s_k+s_{k+1})}\end{bmatrix}$$$$B_{k+1} = \begin{bmatrix}E_k & 0 & 0 \\ 0 & E_{k+1} & 0 \\ 0 & 0 & A_{k+2}\end{bmatrix}$$

où les $P$ et les $L$ alternent dans la construction (puisque les $L$ subissent aussi la permutation.) La différence entre les processus de Bunch-Parlett et Bunch-Kaufman repose dans le choix du pivot, soit de la permutation $P_k$. Le tout sera exploré plus en détail dans les prochaines sections.

## Bunch-Parlett

La stratégie de Bunch-Parlett pour le choix du pivot est aussi appelée *pivotage complet*. Elle se base sur les valeurs maximales des entrées de la matrice sur et hors diagonale. Le choix du pivot est effectué comme suit;

> Poser   $\alpha = (1+ \sqrt{17})/8$

> Poser   $\mu_0 = \max_{i,j}|a_{ij}| =: |a_{pq}|,\;(q\ge p)$

> Poser $\mu_1 = \max_{i}|a_{ii}| =: |a_{rr}|$

> Si $\mu_1\ge \alpha\mu_0$

>> Utiliser $a_{rr}$ comme pivot $1\times 1$ ($s=1$, les colonnes et rangées $1$ et $r$ sont permutées)

> Sinon

>> Utiliser $\begin{bmatrix} a_{pp} & a_{qp} \\ a_{qp} & a_{qq} \end{bmatrix}$ comme pivot $2\times 2$ ($s=2$, les colonnes et rangées $1$ et $p$ sont permutées, suivies des colonnes et rangées $2$ et $q$)

On peut visualiser l'emplacement des pivots comme suit;

$$ \left(\begin{array}{ccccccc}
    \ddots  & \cdots  & \cdots & \cdots & \cdots & \cdots & \cdots \\
    	\vdots  & a_{rr}  &  &  &  &  &  \\
    	\vdots  &  & \ddots &  &  &  &  \\
    	\vdots  &  &  & a_{pp} & \cdots & a_{qp} &  \\
    	\vdots  &  &  & 	\vdots & \ddots & 	\vdots &  \\
    	\vdots  &  &  & a_{qp} & \cdots & a_{qq} &  \\
    	\vdots  &  &  &  &  &  & \ddots \\
  \end{array}\right)$$ 
  
Il est intéressant de regarder de plus près la valeur de $\alpha$ et la manière dont cette dernière est obtenue. Elle est dérivée directement de la borne sur les éléments des blocs de $B$, elle-même issue des valeurs maximales contenues dans $A$. Comme cette valeur est reprise dans les processus de Bunch-Kaufman ainsi que dans l'alternative du *rook pivoting*, nous trouvons pertinent d'en présenter la brève dérivation ici. À noter que la dérivation s'effectue de manière semblable pour les deux autres processus et mène au même résultat.

### Dérivation de $\alpha$

Dans le cas du pivot $1\times 1$, ce dernier est choisi si $\mu_1 \ge \alpha\mu_0$, i.e $\max_i|a_{ii}| \ge \alpha\max_{ij}|a_{ij}|$. Toutes les mises à jour de $A$ via le complément de Schur sont ainsi bornée; 

$$ |a_{ij}| = |b_{ij} - c_{i1}\frac{1}{e_{11}}c_{1j}| \le \mu_0 +\frac{\mu_0^2}{\mu_1} \le \left(1+\frac{1}{\alpha}\right)\mu_0 $$

On peut borner les valeurs de $|a_{ij}|$ de manière semblable pour le cas du pivot $2\times 2$. On note cette fois le complément de Schur comme

$$a_{ij} = b_{ij} - \begin{bmatrix}c_{i1} & c_{i2}\end{bmatrix}E^{-1}\begin{bmatrix}c_{i1} \\ c_{i2}\end{bmatrix} $$

où 

$$E^{-1} = \frac{1}{det(E)}\begin{bmatrix}e_{22} & -e_{12} \\ -e_{21} & e_{11}\end{bmatrix} $$

Par symétrie de $E$

$$det(E) = e_{11}e_{22} - e_{21}^2 \le \mu_1^2-\mu_0^2 \le (\alpha^2-1)\mu_0^2 $$

Il est alors posé que $\alpha\in(0,1)$, de telle sorte que $|det(E)|\ge (1-\alpha^2)\mu_0^2$. Il est alors possible de borner supérieurement $E^{-1}$ dans le complément de Schur. En effet

$$|E^{-1}|\le \frac{1}{(1-\alpha^2)\mu_0^2}\begin{bmatrix}\alpha & 1 \\ 1 & \alpha \end{bmatrix}$$

et donc

$$|a_{ij}|\le \mu_0+\frac{1(1+\alpha)\mu_0^2}{(1-\alpha^2)\mu_0}=\left(1+\frac{2}{1-\alpha}\right)\mu_0$$

Finalement, pour obtenir la valeur de $\alpha$, le multiplicateur de $\mu_0$ dans la borne du pivot de $2\times 2$ est rendu équivalent à deux fois le multiplicateur de $\mu_0$ dans la borne du pivot de $1\times 1$, soit

$$ \left(1+\frac{1}{\alpha}\right)^2 =  \left(1+\frac{2}{1-\alpha}\right)$$

Ce système peut être résolu et mène à deux valeurs de $\alpha$, parmi lesquelles on choisi la valeur positive, qui est bien $\alpha=(1+\sqrt{17})/8$. 

Il s'agit d'une dérivation assez simple d'une valeur reprise dans chacune des implémentations auxquelles ce projet s'intéresse. Le concept de choix de pivot et de borne sur l'augmentationd des éléments est aussi présent dans d'autres types de factorisation et dans des méthodes de base comme l'élimination de Gauss. 

### Pseudo-code

Pour l'implémentation, on combine le choix de $p$ à la mise en place de base du problème, vue dans la première section du rapport. Le pseudo-code suivant illustre la stratégie d'implémentation *in-place* de cet algorithme, présentée dans la @sec-implementation.

\begin{algorithm}[H]
\DontPrintSemicolon
\SetAlgoLined
\KwResult{$PAP^T = LBL^T$}
\SetKwInOut{Input}{Input}\SetKwInOut{Output}{Output}
\Input{A hermitienne indéfinie}
\Output{A modifiée, P}
\BlankLine
$\alpha = (1+ \sqrt{17})/8$ \;
$k = 1$ \;
\While{$k \le n$}{
    $@view A[k:n,k:n]$ \;
    $\mu_1 = \max_i |a_{ii}| := |a_{rr}|$ \;
    $\mu_0 = \max_{ij} |a_{ij}| := |a_{pq}|$ \;
    \eIf{$\mu \ge \alpha\mu_0$}{
        $a_{rr}$ est le pivot $1\times 1$, $s=1$ \;
        Permuter les lignes et colonnes $k$ et $r$ dans $A$ \;
        Permuter les entrées $k$ et $r$ dans $P$ \;
        Insérer le bloc $E$ dans $A[k,k]$ \;
        Insérer la colonne $L$ dans  $A[(k+1):n,k]$ \;
        Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
        $k\;+= 1$ \;
        Mettre à jour la vue sur $A$ \;
    }{
        $a_{pq}$ est le pivot $2\times 2$, $s=2$\;
        Permuter les lignes et colonnes $k$ et $p$ dans $A$ \;
        Permuter les lignes et colonnes $k+1$ et $q$ dans $A$ \;
        Permuter les entrées $k$ et $p$ dans $P$ \;
        Permuter les entrées $k+1$ et $q$ dans $P$ \;
        Insérer le bloc $E$ dans $A[k:(k+1),k:(k+1)]$ \;
        Insérer les colonnes de $L$ dans  $A[(k+1):n,k:(k+1)]$ \;
        Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
        $k\;+=2$ \;
        Mettre à jour la vue sur $A$ \;
    }
}
\caption{Factorisation de Bunch-Parlett (pivotage complet)}
\end{algorithm}

## Bunch-Kaufman

La stratégie de Bunch-Kaufman pour le choix du pivot est aussi appelée *pivotage partiel*. Comme dans la stratégie de Bunch-Parlett, elle se base sur les valeurs maximales des entrées de la matrice sur et hors diagonale. La différence repose dans le fait qu'elle évite le scannage complet de la matrice pour faire son choix, le décortiquant plutôt en 3 sections de recherche beaucoup plus petite. Le choix du pivot est effectué comme suit;

> Poser   $\alpha = (1+ \sqrt{17})/8$

> Poser   $\omega_1 = \max_{i}|a_{i1}|$ pour $i$ sous diagonale
  
> Si $\omega_1=0$, passer à la sous-matrice suivante.

> Sinon

>> Si $|a_{11}|\ge \alpha\omega_1$

>>> Utiliser $a_{11}$ comme pivot $1\times 1$ ($s=1$, aucune permutation)

>> Sinon

>>> Poser $r$, l'index de la valeur maximale dans la colonne 1

>>> Poser $\omega_r = \max_{i}|a_{ir}|$ pour $i$ sous diagonale

>>> Si $|a_{11}|\omega_r \ge \alpha\omega_1^2$

>>>> Utiliser $a_{11}$ comme pivot $1\times 1$ ($s=1$, aucune permutation)

>>> Sinon 

>>>> Si $|a_{rr}| \ge \alpha\omega_r$

>>>>> Utiliser $a_{rr}$ comme pivot $1\times 1$ ($s=1$, les colonnes et rangées $1$ et $r$ sont permutées)

>>>> Sinon

>>>>> Utiliser $\begin{bmatrix} a_{11} & a_{r1} \\ a_{r1} & a_{rr} \end{bmatrix}$ comme pivot $2\times 2$ ($s=2$, les colonnes et rangées $2$ et $r$ sont permutées)

On peut visualiser l'emplacement des pivots comme suit;

$$ \left(\begin{array}{cccccc}
    a_{11}  & \cdots  & a_{r1}(\omega_1) & \cdots & \cdots & \cdots \\
    	\vdots  &  & \vdots &  &  & \\
    	a_{r1}(\omega_1) & \cdots & a_{rr} & \cdots & a_{ir}(\omega_r) & \cdots \\
    	\vdots  &  & \vdots &  &  & \\
    	\vdots  &  & a_{ir}(\omega_r) &  &  & \\
    	\vdots  &  & \vdots &  &  &  \\
  \end{array}\right)$$ 

### Pseudo-code

Pour l'implémentation, on reprend la majorité de ce qui a été fait pour Bunch-Parlett, mais en ajustant le choix de $p$. Le pseudo-code suivant illustre la stratégie d'implémentation *in-place* de cet algorithme, présentée dans la @sec-implementation.

\begin{algorithm}[H]
\DontPrintSemicolon
\SetAlgoLined
\KwResult{$PAP^T = LBL^T$}
\SetKwInOut{Input}{Input}\SetKwInOut{Output}{Output}
\Input{A hermitienne indéfinie}
\Output{A modifiée, P}
\BlankLine
$\alpha = (1+ \sqrt{17})/8$ \;
$k = 1$ \;
\While{$k < n-1$}{
  $@view A[k:n,k:n]$ \;
  $\omega_1 = \max_i|a_{i1}|$ pour $i$ sous la diagonale \;
  \eIf{$\omega_1=0$}{
    Passer à la sous-matrice suivante\;
  }{
    \eIf{$|a_{11}|\ge \alpha\omega_1$}{
      $a_{11}$ est le pivot $1\times 1$, $s=1$ \;
      Insérer le bloc $E$ dans $A[k,k]$ \;
      Insérer la colonne $L$ dans  $A[(k+1):n,k]$ \;
      Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
      $k\;+= 1$ \;
      Mettre à jour la vue sur $A$ \;
  }{ 
      $r=\text{index}(\max_i|a_{i1}|)$ \;
      $\omega_r=\max_i|a_{ir}|$ pour $i$ sous la diagonale \;

  \eIf{$|a_{11}| \omega_r \ge \alpha\omega_1^2$}{
      $a_{11}$ est le pivot $1\times 1$, $s=1$ \;
      Insérer le bloc $E$ dans $A[k,k]$ \;
      Insérer la colonne $L$ dans  $A[(k+1):n,k]$ \;
      Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
      $k\;+= 1$ \;
      Mettre à jour la vue sur $A$ \;
    }{
            \eIf{$|a_{rr}|\ge \alpha\omega_r$}{
              $a_{rr}$ est le pivot $1\times 1$, $s=1$ \;
              Permuter les lignes et colonnes $k$ et $r$ dans $A$ \;
              Permuter les entrées $k$ et $r$ dans $P$ \;
              Insérer le bloc $E$ dans $A[k,k]$ \;
              Insérer la colonne $L$ dans  $A[(k+1):n,k]$ \;
              Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
              $k\;+= 1$ \;
              Mettre à jour la vue sur $A$ \;
            }{
              $a_{r1}$ est le pivot $2\times 2$, $s=2$\;
        Permuter les lignes et colonnes $k+1$ et $r$ dans $A$ \;
        Permuter les entrées $k+1$ et $r$ dans $P$ \;
        Insérer le bloc $E$ dans $A[k:(k+1),k:(k+1)]$ \;
        Insérer les colonnes de $L$ dans  $A[(k+1):n,k:(k+1)]$ \;
        Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
        $k\;+=2$ \;
        Mettre à jour la vue sur $A$ \;
            }
          }

        }
    }
}
\caption{Factorisation de Bunch-Kaufman (pivotage partiel)}
\end{algorithm}

## Bunch-Kaufman avec *Rook pivoting*

La stratégie de *Rook pivoting* est utilisée lorsque l'on veut éviter que la norme de $L$ soit trop grande (ce qui peut générer des instabilités dans certains algorithmes.) Plusieurs éléments du processus sont les mêms que pour Bunch-Kaufman, mais le processus comporte une portion itérative. Le choix du pivot est effectué comme suit;

> Poser   $\alpha = (1+ \sqrt{17})/8$

> Poser   $\omega_1 = \max_{i}|a_{i1}|$ pour $i$ sous diagonale
  
> Si $\omega_1=0$, passer à la sous-matrice suivante.

> Sinon

>> Si $|a_{11}|\ge \alpha\omega_1$

>>> Utiliser $a_{11}$ comme pivot $1\times 1$ ($s=1$, aucune permutation)

>> Sinon

>>> $i=1$

>>> Répéter jusqu'au choix d'un pivot

>>>> Poser $r$, l'index de la valeur maximale dans la colonne i

>>>> Poser $\omega_r = \max_{i}|a_{ir}|$ pour $i$ sous diagonale

>>>> Si $|a_{rr}| \ge \alpha\omega_r$

>>>>> Utiliser $a_{rr}$ comme pivot $1\times 1$ ($s=1$, les colonnes et rangées $1$ et $r$ sont permutées)

>>>> Sinon 

>>>>> Si $\omega_i=\omega_r$

>>>>>> Utiliser $\begin{bmatrix} a_{ii} & a_{ri} \\ a_{ri} & a_{rr} \end{bmatrix}$ comme pivot $2\times 2$ ($s=2$, les colonnes et rangées $1$ et $i$ sont permutées, suivies des colonnes et rangées $2$ et $r$)

>>>>> Sinon

>>>>>> $i=r$, $\omega_i=\omega_r$

Si un pivot $1\times 1$ est trouvé, le pivot est choisi directement. Sinon, le processus cherche un pivot $a_{ri}$ tel que $|a_{ri}|$ est le maximum dans la rangée $r$ et le maximum dans la colonne $i$. 

### Pseudo-code

Le pseudo-code est encore une fois semblable à celui des processus précédent, à la différence de la boucle `while` utilisée dans le choix du pivot. Il illustre la stratégie d'implémentation *in-place* de cet algorithme, présentée dans la @sec-implementation.

\begin{algorithm}[H]
\DontPrintSemicolon
\SetAlgoLined
\KwResult{$PAP^T = LBL^T$}
\SetKwInOut{Input}{Input}\SetKwInOut{Output}{Output}
\Input{A hermitienne indéfinie}
\Output{A modifiée, P}
\BlankLine
$\alpha = (1+ \sqrt{17})/8$ \;
$k = 1$ \;
\While{$k < n - 1$}{
  $@view A[k:n,k:n]$ \;
  $\omega_1 = \max_i|a_{i1}|$ pour $i$ sous la diagonale \;
  \eIf{$\omega_1=0$}{
    Passer à la sous-matrice suivante \;
  }{
    \eIf{$|a_{11}| \ge \alpha \omega_1 $}{
      $a_{11}$ est le pivot $1\times 1$, $s=1$ \;
      Insérer le bloc $E$ dans $A[k,k]$ \;
      Insérer la colonne $L$ dans  $A[(k+1):n,k]$ \;
      Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
      $k\;+= 1$ \;
      Mettre à jour la vue sur $A$ \; 
  }{
      $j=1$ \;

  \While{Un pivot n'a pas été choisi}{
    $r=\text{index}(\max_i|a_{ij}|)$ \;
    $\omega_r=\max_i|a_{ir}|$ pour $i$ sous la diagonale \;
    \eIf{$|a_{rr}| \ge \alpha \omega_r$}
    {
      $a_{rr}$ est le pivot $1\times 1$, $s=1$ \;
      Permuter les lignes et colonnes $k$ et $r$ dans $A$ \;        Permuter les entrées $k$ et $r$ dans $P$ \;
      Insérer le bloc $E$ dans $A[k,k]$ \;
      Insérer la colonne $L$ dans  $A[(k+1):n,k]$ \;
      Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
      $k\;+= 1$ \;
      Mettre à jour la vue sur $A$ \;}{

  \eIf{$\omega_i=\omega_r$}{
    $a_{rj}$ est le pivot $2\times 2$, $s=2$\;
    Permuter les lignes et colonnes $1$ et $j$ dans $A$ \;
    Permuter les lignes et colonnes $2$ et $r$ dans $A$ \;
    Permuter les entrées $1$ et $j$ dans $P$ \;
    Permuter les entrées $2$ et $r$ dans $P$ \;
    Insérer le bloc $E$ dans $A[k:(k+1),k:(k+1)]$ \;
    Insérer les colonnes de $L$ dans  $A[(k+1):n,k:(k+1)]$ \;
    Mettre à jour le bloc inférieur droit de $A$ selon le complément de Schur \;
    $k\;+=2$ \;
    Mettre à jour la vue sur $A$ \;
  }{
    $j=r$ \;
    $\omega_j=\omega_r$
  }
      }
  }    
  }
  }
}
\caption{Factorisation avec rook-pivoting}
\end{algorithm}

# Implémentation {#sec-implementation}

## Environnement

```{julia}
#| output: false
using Pkg
Pkg.activate("Projet_env")
Pkg.add("BenchmarkTools")
Pkg.add("SuiteSparseMatrixCollection")
Pkg.add("MatrixMarket")
Pkg.add("PrettyTables")

using LinearAlgebra, SparseArrays
using MatrixMarket
using SuiteSparseMatrixCollection
using Test
using BenchmarkTools
using PrettyTables
```

## Stratégies d'optimisation {#sec-strategies}

Différentes stratégies ont été adoptées pour optimiser les performances des fonctions créées, autant d'un point de vue mémoire que vitesse d'exécution.

Tout d'abord, pour se conformer aux normes présentes dans Julia, deux versions de chaque algorithme ont été implémentées. La première renvoie les matrices $L$ et $B$ ainsi qu'un vecteur des permutations effectuées $vec_P$ au sein d'une `struct`. La deuxième écrase la matrice $A$ afin de stocker les membres de la factorisation - le nom de cette dernière contient ainsi un `!` pour signifier la modification des éléments d'entrée.  

```{julia}
#| output: false
struct LBL{T}
  """
  Structure pour une matrice factorisée selon PAP' = LBL' (Bunch-Parlett et Bunch-Kaufman)
  """
  L::UnitLowerTriangular{T, Matrix{T}}
  B::Hermitian{T, Tridiagonal{T, Vector{T}}}
  vec_P::Vector{Int}
end
```

La première version permet un accès élégant à une structure contenant toutes les quantités relatives à la factorisation, alors que la seconde version permet de limiter davantage les allocations en stockant directement les matrices $B$ et $L$ dans les emplacements mémoire de $A$ tout au long de celle-ci. Le schéma suivant illustre cela : les blocs bleus représentent les blocs de la matrice $B$ et les verts les colonnes de la matrices $L$. Toutes les valeurs au dessus de la diagonale sont automatiquement nulles puisque l'on utilise des matrices triangulaires inférieures afin de représenter les matrices hermitiennes traitées.

$$ A = \left(\begin{array}{ccccccc}
    \Box  & \Box  & \Box & \Box & \Box & \Box & \Box \\
    \Box  & \Box  & \Box & \Box & \Box & \Box & \Box \\
    \Box  & \Box  & \Box & \Box & \Box & \Box & \Box \\
    \Box  & \Box  & \Box & \Box & \Box & \Box & \Box \\
    \Box  & \Box  & \Box & \Box & \Box & \Box & \Box \\
    \Box  & \Box  & \Box & \Box & \Box & \Box & \Box \\
    \Box  & \Box  & \Box & \Box & \Box & \Box & \Box \\
  \end{array}\right) \to \left(\begin{array}{ccccccc}
    \x \Box  & 0  & 0 & 0 & 0 & 0 & 0 \\
    \y \Box   & \x \Box  & 0 & 0 & 0 & 0 & 0 \\
    \y \Box   & \x \Box & \x \Box & 0 & 0 & 0 & 0 \\
    \y \Box   & \y \Box   & \y \Box  & \x \Box & 0 & 0 & 0 \\
    \y \Box  &  \y \Box  & \y \Box & \y \Box & \x \Box & 0 & 0 \\
    \y \Box  &  \y \Box  & \y \Box & \y \Box & \x \Box & \x \Box & 0 \\
    \y \Box  &  \y \Box  & \y \Box & \y \Box & \y \Box & \y \Box & \x \Box \\
  \end{array}\right) $$ 

La position de chacun des blocs $2 \times 2$ est stockée dans le vecteur `vec_2by2`, car il suffit de les connaître pour être en mesure d'extraire les matrices $B$ et $L$ de cette matrice $A$ compacte finale. En effet, lorsqu'on tombe sur un bloc $2 \times 2$, l'élément de sous-diagonale du bloc appartient à $B$, ce qui indique que l'élément correspondant de sous-diagonale de $L$ est un $0$, car $L$ possède un bloc identité de taille $2 \times 2$ sur sa diagonale. Autrement, les éléments diagonaux appartiennent à $B$ et les éléments sous-diagonaux appartiennent à $L$. Une fonction `extract_L_and_B_from_LBL_inplace` a été créée pour permettre à l'utilisateur d'extraire $B$ et $L$ à partir de ce vecteur et de la matrice $A$. 

```{julia}
#| output: false
function extract_L_and_B_from_LBL_inplace(A, vec_2by2)
  """
  Récupère la matrice L et B à partir de la forme compacte de la factorisation LBL'
    Entrée : - Matrice A sous la forme compacte de la factorisation LBL'
             - Vecteur de position des blocs diagonaux 2x2 vec_2by2
    Sortie : - Matrice L triangulaire inférieure avec diagonale de 1
             - Matrice B tridiagonale hermitienne
  """
  n = size(A, 1)
  T = eltype(A)
  subdiagonal = zeros(T, n-1)
  diagonal = zeros(T, n)
  L = UnitLowerTriangular(Matrix{T}(I, n, n))

  i_diagonal = 1
  while i_diagonal < n - 1
    if i_diagonal in vec_2by2
      # Matrice B
      subdiagonal[i_diagonal], subdiagonal[i_diagonal+1] = A[i_diagonal+1, i_diagonal], 0
      diagonal[i_diagonal], diagonal[i_diagonal + 1] = A[i_diagonal, i_diagonal], A[i_diagonal+1, i_diagonal+1]

      # Matrice L
      L[i_diagonal + 2:n, i_diagonal] .= A[i_diagonal + 2:n, i_diagonal]
      L[i_diagonal + 2:n, i_diagonal + 1] .= A[i_diagonal + 2:n, i_diagonal + 1]

      # Prochain bloc
      i_diagonal += 2
    else
      # Matrice B
      subdiagonal[i_diagonal] = 0
      diagonal[i_diagonal] = A[i_diagonal, i_diagonal]

      # Matrice L
      L[i_diagonal + 1:n, i_diagonal] .= A[i_diagonal + 1:n, i_diagonal]

      # Prochain bloc
      i_diagonal += 1
    end
  end

  # Dernier bloc
  if i_diagonal == n - 1
    subdiagonal[i_diagonal] = A[i_diagonal+1, i_diagonal]
    diagonal[i_diagonal], diagonal[i_diagonal+1]  = A[i_diagonal, i_diagonal], A[i_diagonal+1, i_diagonal+1]
  else
    diagonal[i_diagonal] = A[i_diagonal, i_diagonal]
  end

  B = Hermitian(Tridiagonal(subdiagonal, diagonal, conj(subdiagonal)))

  return L, B
end
```

Dans les deux versions, le caractère hermitien de la matrice $A$ en entrée est exploité pour diminuer le stockage mémoire ainsi que le temps d'exécution. En effet, comme mentionné précédemment, la matrice d'entrée est établie comme triangulaire inférieure dans l'optique de limiter l'espace mémoire ainsi que de s'assurer que la matrice reste parfaitement hermitienne. Ce format est compatible avec les matrices hermitiennes, car il suffit de considérer que les éléments du triangle supérieur sont les transposés conjugués des éléments du triangle inférieur. Bien qu'il existe des formats `Symetric`ou `Hermitian`en Julia, ceux-ci présentent des blocages internes contre les modifications de leurs éléments, ce qui n'est pas pratique pour le traitement optimal de la factorisation. Le type `LowerTriangular` n'a pas de tels blocages, d'où son utilisation ici. Qui plus est, la matrice $L$ est aussi établie comme triangulaire inférieure avec une diagonale de 1 de par sa nature, et la matrice $B$ est établie comme hermitienne tridiagonale afin de minimiser l'espace mémoire en ne stockant que la diagonale et la sous-diagonale. Pour $B$, le type `Hermitian` peut être utilisé puisque l'on a jamais besoin de modifier ses éléments directement dans le contexte actuel. Par ailleurs, les permutations effectuées sont stockées dans un vecteur $vec_P$ plutôt que dans une matrice de permutation complète $P$, ce qui réduit également l'espace mémoire utilisé. Des fonctions personalisées ont été créées afin de pouvoir appliquer l'action de $P$ et de $P^T$ sur une matrice donnée seulement à partir de $vec_P$, de tranposer ce dernier et d'en extraire la matrice $P$ correspondante si besoin.

En outre, on note que les algorithmes de factorisation en eux-mêmes ont été conçus et optimisés afin d'exploiter le caractère hermitien des matrices auxquelles ils s'appliquent. Par exemple, lors de la recherche des valeurs absolues maximales hors diagonales pour Bunch-Parlett, seule la moitié inférieure de la matrice a besoin d'être parcourue. On ne regarde donc que ce qui est sous la diagonale, car ce qui est au-dessus n'en est que le transposé conjugué.

Sinon, des `views` sont utilisées pour limiter le nombre d'allocations et des boucles `for` sont fréquemment utilisées pour faire des modifications éléments par éléments et ainsi éviter la création de vecteurs temporaires. Par exemple, pour les pivots de taille $2\times 2$, le complément de Schur est calculé via son expression algébrique pour éviter les allocations de vecteurs. Il en va de même pour la mise à jour de $L$ dans le cas $2\times 2$. De plus, des variables temporaires sont souvent utilisées afin d'éviter de recalculer des quantités. 

Par ailleurs, il est à noter que la notation `i_diagonal` a été préférée à `k` dans le code pour éviter toute confusion avec une troisième dimension ou avec un indice de boucle. 

Finalement, les différentes versions individuelles de chacun de ces algorithmes ont été regroupées en une version générale permettant de choisir quel algorithme utiliser. Ceci a été possible en déplaçant le choix de pivot dans des fonctions propres à chaque algorithme, car le reste de la procédure est similaire entre ces derniers.

## Factorisation générale

Les fonctions suivantes implémentent de façon générale la factorisation de Bunch-Parlett (pivotage complet), de Bunch-Kaufman (pivotage partiel) et de Bunch-Kaufman avec *rook pivoting* selon les deux approches mentionnées précédemment. La factorisation à appliquer est déterminée par le paramètre d'entrée `pivoting_strategy`.

```{julia}
#| output: false
{{< include Facto_LBL.jl >}}
```

# Tests et performances {#sec-tests}

Trois types de tests ont été effectués sur les implémentations:  

1. La validité des factorisations ainsi que leur compatibilité avec différents types de données (`Float64`, `ComplexF64` et `BigFloat`) est établie.  
2. Les performances (nombre d'allocations et temps d'exécution) des différentes implémentations sont caractérisées à l'aide du module `BenchmarkTools`.  
3. La capacité à résoudre correctement des systèmes linéaires est établie, en particulier sur des systèmes de point de selle.  

Dans le fichier `Code`, la section *Utilitaire* liste plusieurs des fonctions nécessaires au roulement de ces tests, en particulier les tests sur les types de données. Les tests sont ensuite présentés dans l'ordre mentionnés, suite aux implémentations. 

## Validité et compatibilité

Pour établir la validité des fonctions sur différents types de données, 25 matrices de forme 

$$ K = \begin{bmatrix} I & A \\ A^* & 0 \end{bmatrix} $$

sont créées l'une après l'autre, où $A$ est aléatoire et de taille $50\times 25$. Les matrices sont factorisées et leur reconstruction par la factorisation $P^TLBL'P$ est comparé à $A$ via la norme de leur différence. La tolérance des tests est de $sqrt(eps(T))$, où $T$ est le type de donnée. Il est aussi validé que le type des données contenues dans $L$ et $B$ est le même que celui des éléments de $A$. Toutes les implémentations passent les tests en ce qui concerne le type de données supportées.

## Benchmarking

Similairement à précédemment, des matrices $K$ de différentes tailles sont construites à partir d'une matrice $A$ aléatoire. Celles-ci sont utilisées en entrée pour effectuer le `Benchmarking` des différentes implémentations. La factorisation est également effectuée en utilisant la fonction `bunchkaufman` de Julia, qui appelle LAPACK. L'option `rook` de cette dernière devait être testée, mais elle ne semble pas être reconnue par la fonction - il semble y avoir un décalage entre la documentation en ligne et le code source de la version de Julia utilisée ici. Les résultats obtenus sont présentés ci-dessous et commentés dans la @sec-discussion.

```{julia}
#| echo: false
{{< include Table_Benchmark.jl >}}
```

On note que ces tests de performance ont été effectués sur les versions individuelles de chacun des algorithmes de factorisation plutôt que sur la version générale qui les combine et qui a été présentée précédemment. Pour une raison inconnue, les marqueurs de performance retournés par `BenchmarkTools` ne sont plus très fiables pour cette version générale. En effet, des phénonèmes contradictoires ont été observés, où la mémoire et le nombre d'allocations estimés augmentent pour certains algorithmes, alors que le code est le même que dans les versions individuelles pour lesquelles ces quantités sont minimes et semblables. En investiguant plus précisément, on s'aperçoit que l'augmentation existe pour Bunch-Kaufman et Bunch-Kaufman avec *Rook Pivoting*, mais pas pour Bunch-Parlett, et que celle-ci vient spécifiquement du recours aux fonctions de choix de pivot correspondantes. Or, en caractérisant cesdites fonctions de choix de pivot, il s'avère que c'est Bunch-Parlett qui est décrit comme utilisant beaucoup de mémoire et d'allocations alors que c'est totalement l'inverse pour Bunch-Kaufman et Bunch-Kaufman avec *Rook Pivoting*, ce qui est contradictoire. Ceci est aussi incohérent avec le fait que leurs opérations sont exactement les mêmes que dans les versions individuelles où elles ne semblent pas générer d'allocations. Par ailleurs, en modifiant cesdites fonctions afin d'essayer de comprendre cela, on s'aperçoit qu'en supprimant les conditions `if else` pour le `return` du choix de pivot de Bunch-Parlett et en effectuant directement ce `return`, la mémoire et le nombre d'allocations augmentent drastiquement. Pourtant, on n'a fait ici que supprimer des opérations en gardant le reste tel quel, il est donc très étrange que subitement la mémoire consommée et le nombre d'allocations augmentent, et ceci n'est qu'un exemple parmi plusieurs autres. Par contre, le temps d'exécution n'est pas affecté par cela et est sensiblement le même que pour la version générale.

## Résolution de systèmes linéaires

Pour la résolution de systèmes linéaires, deux types de tests sont effectués. D'abord, des matrices $K$ hermitiennes indéfinies aléatoires sont construites de la même manière que précédemment, couplées à des vecteurs $b$ qui sont définis de manière aléatoire. Le tout forme des systèmes de point de selle à résoudre, et les solutions obtenues sont comparées aux solutions obtenues par factorisation `qr` sur les problèmes au moindres carrés en étant la source. La définition de la fonction `\` a été étendue pour spécifiquement s'appliquer à la structure de la factorisation $PAP^T = LBL'$.

```{julia}
#| output: false
{{< include Resol_systemes.jl >}}
```

Les tests sont effectués sur 100 problèmes aléatoires différents de type `BigFloat` complexe. L'erreur moyenne sur $x$ est présentée ci-dessous. 

```
Average error on solution:
 - bunch_parlett : 1.845391976297269e-72
 - bunch_parlett! : 1.845391976297269e-72
 - bunch_kaufman : 1.9192185697707733e-76
 - bunch_kaufman! : 1.9192185697707733e-76
 - bunch_kaufman_rook : 1.1230644109253653e-74
 - bunch_kaufman_rook! : 1.1230644109253653e-74
 - bunch_kaufman de LAPACK : 2.830305448329891e-76
 - bunch_kaufman! de LAPACK : 2.830305448329891e-76
```

Ensuite, quatre problèmes issus de `MatrixMarket` (`Suite Sparse Collection`) sont résolus avec les différentes implémentations, soient `ch5-5-b1`, `ch4-4-b1`, `ch4-4-b2` et `n3c5-b2`. Les systèmes de point de selle sont générées comme dans les sections précédentes, mais en incluant cette fois-ci une légère perturbation dans le bloc inférieur droit des matrices $K$ lorsqu'il s'agit de résoudre avec les fonctions `bunchkaufman` et `bunchkaufman!` standards de Julia. En effet, autrement celles-ci lèvent une exception de singularité pour certains problèmes. En effet, ces problèmes ne sont pas tous de rang plein, et ainsi la résolution par factorisation ne retourne pas nécessairement la solution de moindre norme. De ce fait, la norme du résidu du problème au moindre carré est comparée. On dénote "l'erreur sur le résidu" comme la norme de la différence entre le résidu retourné par factorisation LBL' et celui retourné par factorisation QR. Les résultats obtenus sont présentés ci-dessous. 

```
Average error on residual for ch5-5-b1 :
 - bunch_parlett : 0.0
 - bunch_parlett! : 0.0
 - bunch_kaufman : 1.3192499109564437e-5
 - bunch_kaufman! : 1.3192499109564437e-5
 - bunch_kaufman_rook : 1.3192499109564437e-5
 - bunch_kaufman_rook! : 1.3192499109564437e-5
 - bunch_kaufman de LAPACK : 0.0
 - bunch_kaufman! de LAPACK : 0.0
Average error on residual for ch4-4-b1 :
 - bunch_parlett : 0.0
 - bunch_parlett! : 0.0
 - bunch_kaufman : 8.213358342281651e-5
 - bunch_kaufman! : 8.213358342281651e-5
 - bunch_kaufman_rook : 8.213358342281651e-5
 - bunch_kaufman_rook! : 8.213358342281651e-5
 - bunch_kaufman de LAPACK : 0.0
 - bunch_kaufman! de LAPACK : 0.0
Average error on residual for ch4-4-b2 :
 - bunch_parlett : 0.0
 - bunch_parlett! : 0.0
 - bunch_kaufman : 0.0
 - bunch_kaufman! : 0.0
 - bunch_kaufman_rook : 0.0
 - bunch_kaufman_rook! : 0.0
 - bunch_kaufman de LAPACK : 0.0
 - bunch_kaufman! de LAPACK : 0.0
Average error on residual for n3c5-b2 :
 - bunch_parlett : 0.0
 - bunch_parlett! : 0.0
 - bunch_kaufman : 0.0
 - bunch_kaufman! : 0.0
 - bunch_kaufman_rook : 0.0
 - bunch_kaufman_rook! : 0.0
 - bunch_kaufman de LAPACK : 0.0
 - bunch_kaufman! de LAPACK : 0.0
```

# Discussion {#sec-discussion}

## Implémentations

D'un point de vue théorique, un théorème permet d'assurer la stabilité du processus de Bunch-Kaufman. Ce théorème assure que pour $(A+\Delta A)\hat{x}=b$ la solution du système $\hat{x}$, la perturbation sur la norme de $A$ est bornée supérieurement comme $\parallel \Delta A\parallel_M \le p(n)\rho_n u\parallel A\parallel_M + O(u^2)$ où $p$ est quadratique. Ce résultat s'applique si le système est résolu par élimination gaussienne ou en utilisant l'inverse.

Pour tous les processus d'intérêt dans ce projet, un autre résultat intéressant est le suivant:

$$ \frac{\parallel x-\hat{x}\parallel_\infty}{\parallel x \parallel_\infty} \le p(n)u\;\text{cond}(A)\;\text{cond}(|D| |L^T|)+O(u^2) $$

$\text{cond}(|D| |L^T|)$ n'est pas borné pour le pivotage partiel, mais il l'est pour le *rook pivoting* et cette méthode est donc en théorie moins sensible à un $A$ initial moins bien conditionné. 

D'un point de vue expérimental, on observe d'abord que toutes les implémentations de ces factorisations permettent de reconstruire la matrice $A$ en entrée avec une précision d'au moins $1e^{-8}$ et ce, pour divers types de données. Qui plus est, les matrices $L$ et $B$ sont respectivement triangulaire inférieure et hermitienne tridiagonale. Les implémentations semblent donc valides.

Ensuite, le `Benchmarking` indique qu'elles effectuent la factorisation avec moins d'allocations que les versions standard de Julia qui appellent LAPACK. Elles semblent donc très bien optimisées par rapport aux allocations. De plus, pour chaque algorithme de factorisation, la version `!` génère bel et bien moins d'allocations que la version avec une `struct`, ce qui est attendu. Dans le contexte présent, on note qu'il est impossible de n'avoir aucune allocation, car il y a toujours quelques objets dont la création est nécessaire (vecteur permutation, vecteur de position des blocs $2\times 2$, etc.). Qui plus est, le reste des allocations n'ayant pas été éliminées semblent être généré lors de certaines exécutions d'opérations `-=` pourtant effectuées éléments par éléments dans des boucles `for`. Ces opérations ne semblent pas pouvoir être optimisées davantage et il est assez surprenant qu'elles soient parfois source d'allocations. Peut-être est-ce lié à ce que les fonctions de `BenchmarkTools` considèrent comme une allocation et à la manière dont elles les détectent et les identifient.

Par contre, on remarque que la mémoire allouée augmente en fonction de la taille (ce qui est attendu) et qu'elle est similaire entre les implémentations. La seule exception est qu'à partir de la taille $500 \times 500$, elle devient subitement environ deux fois plus élevée pour les implémentations personalisées avec `struct` que pour celle utilisant LAPACK. Ceci est étrange, surtout considérant que les allocations sont bien plus faibles que pour LAPACK. Or, on remarque que ces allocations, même si très peu nombreuses, augmentent subitement elles aussi à partir de la taille $500 \times 500$. Il y a donc une certaine corrélation ici. Toutefois, le comportement abrupte de cette augmentation suggère un lien avec la façon dont `BenchmarkTools` les estiment, et cette estimation n'est pas toujours cohérente. Effectivement, une augmentation des allocations en fonction de la taille devrait normalement être continue dans le contexte présent. Qui plus est, cela suggère aussi un lien avec les allocations résiduelles mentionnées précédemment, qui semblent être générées par du code qui ne devrait pas en générer à priori. En effet, les seules allocations réelles auxquelles on s'attend sont celles liées à la création de la `struct`, du vecteur permutation, etc, mais ces dernières sont fonction de la taille de l'entrée et devraient donc augmenter en fonction de cette dernière. Le fait que les allocations n'augmentent pas de la taille $75 \times 75$ à la taille $250 \times 250$, puis augmentent subitement à la taille $500 \times 500$, pour ensuite rester constantes à la taille $1000 \times 1000$, indique que les allocations observées sont peut-être entièrement due aux allocations résiduelles, car autrement il aurait fallu qu'elles augmentent au moins partiellement avec la taille de l'entrée. Si c'est bien le cas, alors le mystère de leur comportement se joint à celui de leur existence ayant pour source la façon dont `BenchmarkTools` estime ces quantités.

Par ailleurs, on remarque que les implémentations sont pratiquement aussi rapides que celles de Julia appelant LAPACK pour des matrices $75 \times 75$, donc relativement de petite taille. Puisque LAPACK est en `Fortan` et est ainsi optimisé pour la performance, il était attendu que les implémentations standard en Julia soit plus rapides. Toutefois, il est intéressant de constater que la différence de vitesse n'est pas si significative pour une telle taille matricielle. Bien qu'il reste à tester cela sur des matrices de plus grande taille, ceci indique que les implémentations sont bien optimisées en performance, surtout considérant qu'elles utilisent moins d'allocations, ce qui est d'ailleurs un facteur qui peut contribuer à améliorer la temps d'exécution. En outre, on remarque que Bunch-Parlett est plus lent que Bunch-Kaufman avec *Rook Pivoting*, qui est plus lent que Bunch-Kaufman classique. Ceci est attendu, car Bunch-Parlett utilise une vérification exhaustive des valeurs absolues maximales au sein de la matrice, alors que Bunch-Kaufman avec *Rook Pivoting* utilise une vérification allégée, mais qui reste plus exhaustive que celle utilisée par Bunck-Kaufman classique.

Pour la résolution de problèmes aux moindre carrés aléatoires, l'erreur comparativement à celle trouvée par factorisation `qr` est d'abord extrêmement faible pour toutes les implémentations. Ceci indique leur validité dans la résolution de système linéaire. On remarque même que l'erreur de l'implémentation de Bunch-Kaufman est inférieure à celle obtenue avec l'implémentation de LAPACK, ce qui suggère une plus grande précision. Bunch-Parlett et Bunch-Kaufman avec *Rook Pivoting* présentent une plus grande erreur, bien que la différence demeure minime en `Big Float`. Peut-être Bunch-Kaufman classique est-il plus efficace sur des problèmes aléatoires et ainsi probablement bien conditionnés. De plus, pour chaque implémentation, les versions `struct` et `!` ont la même erreur, y compris pour l'implémentation LAPACK. Ceci est attendu puisque la factorisation est la même dans les deux cas.

Pour les problèmes aux moindres carrés issus de `MatrixMarket`, l'erreur moyenne sur le résidu est tellement faible qu'elle tombe à 0 presque tout le temps. Les seules exceptions concernent Bunch-Kaufman avec ou sans *rook pivoting* pour `ch5-5-b1` et `ch4-4-b1`, bien que les erreurs soient quand même très faibles. Il est difficile d'identifier précisément pourquoi; les deux premiers problèmes sont ceux créés à partir des matrices aux nombres de conditionnement les plus bas, mais aux normes les plus élevées. Le noyau des matrices $A$ de ces deux problèmes est aussi de taille 1, ce qui n'est pas le cas des deux derniers problèmes, pour lesquels la dimension du noyau est plus élevée. Sur ces deux premiers problèmes, on observe également que Bunch-Parlett est plus précis que Bunch-Kaufman, ce qui peut s'expliquer étant donné la vérification plus exhaustive des valeurs absolues maximales qu'utilise Bunch-Parlett. Tout ceci renforce la validité dans la résolution de systèmes linéaires.

## Difficultés rencontrées

Trois difficultées principales ont été rencontrées:  

1. Afin d'effectuer la factorisation en chaîne sur les différents compléments de Schur sujets à des permutations, et de ramener cesdites permutations dans un seul opérateur de permutation qui s'applique à l'ensemble du bloc $LBL'$, il est nécessaire de permuter les lignes de $L$ de façon appropriée au cours de la factorisation. Cela n'est pas nécessairement évident à première vue, et n'est pas toujours explicité dans les sources bibliogaphiques. Ceci se fait explicitement dans la version `struct`, et se fait en permutant directement les éléments des colonnes antérieures de $A$ dans la version `!`.  

2. Afin d'effectuer des permutations de lignes et de colonnes dans une matrice hermitienne dans laquelle seul le triangle inférieur est stocké, il est nécessaire d'adapter l'opération de permutation de façon séquentielle, en permutant parfois une partie de ligne avec une partie de colonne. En effet, puisque le triangle supérieur est le transposé conjugué du triangle inférieur, ses colonnes sont en fait les lignes du triangle inférieur et inversement. Ceci est effectué élément par élément sans allocation grâce à la fonction `perm_r1_et_r2!`.  

```{julia}
#| output: false
function perm_r1_et_r2!(M, r1::Int, r2::Int)
    """
    Modifie une matrice M hermitienne en permutant les lignes et les colonnes d'indices r1 et r2, où r2 >= r1
        Entrée : - Matrice M hermitienne
                 - Indice r1
                 - Indice r2
    """
    if r2 < r1
        error("r2 doit être plus grand ou égal à r1")
    end

    n = size(M, 1)

    M[r1, r1], M[r2, r2] = M[r2, r2], M[r1, r1]
    M[r2, r1] = conj(M[r2, r1])
    for k in r1+1:r2-1
        M[k, r1], M[r2, k] = conj(M[r2, k]), conj(M[k, r1])
    end
    for i in r2+1:n
        M[i, r1], M[i, r2] = M[i, r2], M[i, r1]
    end
    for j in 1:r1-1
        M[r1, j], M[r2, j] = M[r2, j], M[r1, j]
    end
end
```

3. Afin d'optimiser le nombre d'allocations, il a fallu investiguer précisément chaque portion de code afin d'identifier ce qui en générait. Ceci semble avoir révélé que parfois, de simples opérations comme `.*=` appliquées sur une *view*, ou encore un calcul dans lequel se retrouve à la fois des variables et des fonctions comme `abs` ou `conj` appliquées à des variables, sont sources d'allocations. Le tout a donc dû être optimisé au peigne fin, avec beaucoup de recours aux boucles `for` et de création de variables intermédiaires. Qui plus est, le comportement de `BenchmarkTools` reste mystérieux pour la version générale de la factorisation.

# Retour sur les objectifs {#sec-objectifs}

La majorité des objectifs du projet sont accomplis avec la remise de la phase 2. 

1. Comprendre et documenter les factorisations de Bunch-Parlett et Bunch-Kaufman (pivotage complet et pivotage partiel.) Fournir des exemples, des schémas explicatifs, faire des liens avec les éléments vus en classe.
  - Voir la section @sec-description et la section @sec-theorie. 

2. Implémenter ces deux factorisation ainsi que l'alternative du *rook pivoting*. Les comparer et identifier leurs avantages et leurs inconvénients respectifs. 
  - Voir la section @sec-implementation et la section @sec-discussion.
  - Le nombre de flop lui-même n'a pas été comparé directement, d'un point de vue numérique.
  - La sous-section @sec-strategies explique comment les fonctions ont été optimisées pour réduire le temps d'exécution ainsi que le nombre d'allocation.

3. Comparer nos implémentations à celles déjà disponibles dans Julia et tenter d'identifier les sources possibles des différences observées.
  - Voir la section @sec-tests. 
  - Il a été confirmé qu'aucune implémentation de Bunch-Parlett n'existe dans Julia.
  - L'option *rook pivoting* devait être testée, mais ne fonctionnait pas lors de nos tests.
    
4. Joindre la factorisation à des méthodes de résolution de systèmes linéaires. 
  - Voir la section @sec-tests, plus spécifiquement la redéfinition de la fonction `\`.

5. Appliquer l'implémentation à un ensemble de problèmes modèles ainsi qu'à un problème plus spécifique au choix.
  - Voir la section @sec-tests.
  - Différents problèmes ont été créés avec des matrices aléatoires ainsi qu'avec des matrices connues et définies. 

Tel qu'attendu, la majorité du temps a été alloué à l'optimisation des implémentations en Julia et à la revue de littérature. Cette dernière a couvert à la fois la théorie derrière la factorisation et les normes de codage en Julia. Le fait de pouvoir réutiliser des portions de code pour chaque implémentation ainsi que pour les tests a permis de réduire un peu le temps passé sur ces éléments. 


# Références {#sec-references}

[1] : Nicholas J. Higham. Accuracy and Stability of Numerical Algorithms. Society for Industrial
      and Applied Mathematics, second edition, 2002. doi: 10.1137/1.9780898718027. URL
      https://epubs.siam.org/doi/abs/10.1137/1.9780898718027.

[Lien vers le dépôt Github du projet](https://github.com/HortenseBeaudoin/MTH8211_Projet)

# Annexe {#sec-annexe}
## Versions individuelles des algorithmes
### Bunch-Parlett

Les fonctions suivantes implémentent la factorisation de Bunch-Parlett (pivotage complet) selon l'approche de création d'une `struct` et l'approche *in-place*.

```{julia}
#| output: false
{{< include Bunch_Parlett.jl >}}
```

### Bunch-Kaufman

Les fonctions suivantes implémentent la factorisation de Bunch-Kaufman (pivotage partiel) selon l'approche de création d'une `struct` et l'approche *in-place*.

```{julia}
#| output: false
{{< include Bunch_Kaufman.jl >}}
```

### Bunch-Kaufman avec *Rook pivoting*

Les fonctions suivantes implémentent la factorisation avec *rook pivoting* selon l'approche de création d'une `struct` et l'approche *in-place*.

```{julia}
#| output: false
{{< include Rook_Pivoting.jl >}}
```